//*****************************************************************************
// Copyright (c) 2014 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
// 
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
// 
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the  
//   distribution.
// 
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This file was automatically generated by the Tiva C Series PinMux Utility
// Version: 1.0.4
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "toggle_PinMux.h"
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "driverlib/sysctl.h"
#include "driverlib/pin_map.h"
#include "driverlib/rom_map.h"
#include "driverlib/gpio.h"
#include "inc/tm4c123gh6pm.h"


//*****************************************************************************
void
PortFunctionInit(void)
{
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);

    HWREG(GPIO_PORTF_BASE + GPIO_O_LOCK) = GPIO_LOCK_KEY;
    HWREG(GPIO_PORTF_BASE + GPIO_O_CR) = 0x1;

    MAP_GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_0);
    MAP_GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_4);
		
		MAP_GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_1);
	  MAP_GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_2);
	
		GPIO_PORTF_PUR_R |= 0x11;
}

int main(void) {
	PortFunctionInit();
	
	int counter = 0;
	int db1 = 0;
	int db2 = 0;
	
	uint8_t LED2Data = 0x04;
	uint8_t LED1Data = 0x02;

  while(1) {
		if (GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_0) == 0x00 && db1 == 0) {
			counter = counter + 1;
			db1 = 1;
		} if (GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_0) != 0x00 && db1 == 1) db1 = 0;
		
		if (GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_4) == 0x00 && db2 == 0) {
			counter = counter - 1;
			db2 = 1;
		} if (GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_4) != 0x00 && db2 == 1) db2 = 0;
		
		if (counter > 3) counter = 3;
		if (counter < 0) counter = 0;
		
		if (counter == 1 || counter == 3) LED1Data = 0x02;
		else LED1Data = 0x00;

		
		if (counter >= 2) LED2Data = 0x04;
		else LED2Data = 0x00;

		GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, LED1Data);
		GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, LED2Data);
	}
}
